apiVersion: v1
kind: Service
metadata:
  name: {{ include "prayag-new1.fullname" . }}
  labels:
    app: {{ include "prayag-new1.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "prayag-new1.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
